# Generated by Django 5.2.13 on 2026-04-26 10:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlowFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='Name of the imported file', max_length=255, unique=True)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the file was imported')),
                ('record_count', models.IntegerField(default=0, help_text='Number of readings imported from this file')),
            ],
            options={
                'verbose_name': 'Flow File',
                'verbose_name_plural': 'Flow Files',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpan', models.CharField(db_index=True, help_text='Meter Point Administration Number (13 digits)', max_length=13)),
                ('meter_serial_number', models.CharField(db_index=True, help_text='Serial number of the meter', max_length=50)),
                ('reading_value', models.DecimalField(decimal_places=3, help_text='The meter reading value', max_digits=12)),
                ('reading_date', models.DateField(db_index=True, help_text='Date when the reading was taken')),
                ('reading_type', models.CharField(blank=True, help_text='Type of reading (e.g., Normal, Estimate)', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flow_file', models.ForeignKey(help_text='The flow file this reading came from', on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='readings.flowfile')),
            ],
            options={
                'verbose_name': 'Meter Reading',
                'verbose_name_plural': 'Meter Readings',
                'ordering': ['-reading_date', 'mpan'],
                'indexes': [models.Index(fields=['mpan', 'reading_date'], name='readings_me_mpan_a70372_idx'), models.Index(fields=['meter_serial_number', 'reading_date'], name='readings_me_meter_s_cfe3dd_idx')],
            },
        ),
    ]
